### ISSUE TITLE
CANAPP + CAN simulator + IsoTpSend, diagnostic message practice

### ISSUE THREAD

**Issue by mark870329** [autoas/as#8]
Hi, I would like ask why my IsoTpsend can't receive RX message?
and I also do not receive RX message when I implement bootloader demo.

![1](https://user-images.githubusercontent.com/37133520/162907591-6d6fcd1d-309b-49a6-ab0f-7619687c898f.PNG)
![2](https://user-images.githubusercontent.com/37133520/162907625-11aa08aa-da38-4053-a276-bc8fde8ca014.PNG)
![3](https://user-images.githubusercontent.com/37133520/162907627-b6d8b1b7-c614-451b-8d74-c300c70fef77.PNG)

thank you.

**Comment by parai** [comment]
from https://github.com/autoas/ssas-public/blob/master/tools/libraries/isotp/src/isotp_can.c#L81, it was timeout when receiving response. you can try enlarge the default timeout value 5000000 to a lager value to check what's wrong.

**Comment by mark870329** [comment]
Hi, I try to enlarge the default timeout value, but the problem still happen.
I also change error code to -29, but error code is still -99
![6](https://user-images.githubusercontent.com/37133520/162959625-d6d67dc6-0c67-40c4-96b7-2fa54e0a3465.PNG)
![4](https://user-images.githubusercontent.com/37133520/162959629-2d1a11f9-e302-42b9-9a8b-92ab28596aca.PNG)

thank you.

**Comment by parai** [comment]
Hi @mark870329 :
This turns out a bug in the CanTp_Cfg.c for isotp, I forgot to sync the chages from my development repo to this release repo.

This issue should be fixed by commit https://github.com/autoas/ssas-public/commit/bf995e680975dee8f114f35cd532edb488b77844
![image](https://user-images.githubusercontent.com/3183386/165509898-489e2d2a-263f-4863-9d5f-d4aafe77b6f1.png)
